export enum QUERY_KEYS {
  GET_USER = "get-user",
  SEARCH = "search",
  GET_MOVIES = "get-movies",
  GET_ACTORS = "get-actors",
  GET_USER_RATED_MOVIES = "get-user-rated-movies",
  GET_MOVIE_INFO = "get-movie-info",
  GET_MOVIE_ACTORS = "get-movie-actors",
  GET_USER_REVIEWS = "get-user-reviews",
  GET_MOVIE_GENRES = "get-movie-genres",
  GET_SIMILAR_MOVIES = "get-similar-movies",
  GET_ACTOR_INFO = "get-actor-info",
  GET_ACTOR_MOVIES = "get-actor-movies",
  GET_NEWS = "get-news",
}
